/**
* @file   PowLawAcceptance.hxx
* @author Suvayu Ali <Suvayu.Ali@cern.ch>
* @date   Fri May 18 04:01:31 2012
* 
* @brief  This class implements an error function acceptance.
*
*         This code is based on a skeleton code generated by
*         RooClassFactory from RooFit. The functional form and the
*         integral was coded in by hand.
* 
*/


#ifndef __ERFACCEPTANCE_HXX
#define __ERFACCEPTANCE_HXX

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"


class ErfAcceptance : public RooAbsReal {
public:

  ErfAcceptance() {};
  ErfAcceptance(const char *name, const char *title, RooAbsReal& turnon,
		RooAbsReal& time, RooAbsReal& offset);
  ErfAcceptance(const ErfAcceptance& other, const char* name=0);
  virtual ~ErfAcceptance();
  virtual TObject* clone(const char* newname) const;

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,
			      const char* rangeName=0) const;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

  Double_t evaluate() const;

  RooRealProxy _turnon;
  RooRealProxy _time;
  RooRealProxy _offset;

private:

  //  ClassDef(ErfAcceptance,1) // This class implements a power law
			       // acceptance function.
};

#endif	// __ERFACCEPTANCE_HXX
