/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef BDPTACCEPTANCE
#define BDPTACCEPTANCE

// ROOT and RooFit includes
#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"


class BdPTAcceptance : public RooAbsReal {
public:
  BdPTAcceptance() {} ; 
  BdPTAcceptance(const char *name, const char *title,
                 RooAbsReal& _t,
                 RooAbsReal& _beta,
                 RooAbsReal& _slope,
                 RooAbsReal& _offset);
  BdPTAcceptance(const BdPTAcceptance& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new BdPTAcceptance(*this,newname); }
  inline virtual ~BdPTAcceptance() { }
  
protected:
  
  RooRealProxy t ;
  RooRealProxy beta ;
  RooRealProxy slope ;
  RooRealProxy offset ;
  
  Double_t evaluate() const ;
  
private:
  
  ClassDef(BdPTAcceptance,1) // Your description goes here...
    };

#endif
